// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "313b9338-2754-47b0-a624-5b5f64061b81";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onThresholdLowChange();
void onThresholdHighChange();

int moisture;
int thresholdLow;
int thresholdHigh;
bool pump;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(moisture, READ, ON_CHANGE, NULL, 5);
  ArduinoCloud.addProperty(thresholdLow, READWRITE, ON_CHANGE, onThresholdLowChange);
  ArduinoCloud.addProperty(thresholdHigh, READWRITE, ON_CHANGE, onThresholdHighChange);
  ArduinoCloud.addProperty(pump, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
